### ISSUE TITLE
AUR package and some shit scripts for 0.7.0 distro

### ISSUE THREAD

**Issue by kreon** [mikey-austin/greyd#4]
Hi!
I made a PKGBUILD (Arch Linux rules for building package ) for greyd 0.7.0, including integration with systemctl & iptables & some scripts. You may use it for other distros if you want.

And thanks, yeah, I thought about porting spamd a few weeks ago

https://aur.archlinux.org/packages/greyd/

**Comment by mikey-austin** [comment]
Awesome thanks kreon, looks good. I was going to make a systemd greyd.service this weekend!
