### ISSUE TITLE
dnsbl/rbl

### ISSUE THREAD

**Issue by ra1nb0w** [mikey-austin/greyd#6]
during my search for an ipv6 patch I found your project and the spf part is quite nice. what do you think about implementing rbl/dnsbl?

thanks

**Comment by mikey-austin** [comment]
I was indeed thinking about this as well, and I suppose if it can be completely disabled by way of a configure flag, then I don't see an issue.

I am just concious of too many DNS queries slowing things down, but if the administrator is aware of the tradeoffs, then it is definitely useful functionality.

As a side note, I had been playing with the idea of abstracting out these types of checks (SPF, DNSBL, etc.) into a more generic "trap" plugin interface, and possibly embed an interpreter such as Lua. Then these types of plugins can be implemented as Lua scripts, but I was unsure if that would be overkill or not.

**Comment by mikey-austin** [comment]
I have implemented pretty much what I described above, and it is sitting in the *plugins* branch.

Basically I implemented the following:
- implemented a plugin framework in which one may register "spamtraps"
- moved spf functionality into a separate plugin
- implemented a guile/scheme plugin, so plugins can be implemented in lisp
- implemented a simple dnsrbl lookup in lisp (which can be found in commit 9ef8a93)

If you want to try it out, you can load the plugin with the following config (after building it of course).

    plugin guile {
        driver = "greyd_guile.so" # Set proper LD_LIBRARY_PATH
        enable = 1
        # Change the path to your scheme scripts.
        scripts = [ "/home/mikey/workspace/greyd/plugins/guile_scripts/*.scm" ]
    }

Now other spamtraps can be implemented without re-compiling the program. A lua plugin might be cool as well for those not keen on lisp.

I would love to hear what you think!
