### ISSUE TITLE
It misses guidance to enable firewall redirections.

### ISSUE THREAD

**Issue by helioloureiro** [mikey-austin/greyd#7]
Hi,

I started postfix on loopback listening at 25.  Same for greyd on 8025.  And I created the following rules:

iptables -t nat -A PREROUTING -p tcp --dport 25 -d <external IP> -j REDIRECT --to-port 8025

It works fines, but I guess I need to create some chain to allow a connection toward port 25 on white list.  If I manually add a rule before that one, like:

iptables -t nat -A PREROUTING -p tcp -s <whited host> --dport 25 -d <external IP> -j REDIRECT --to-port 25

But I guess it should be automatic.  I miss some direction about that.  Can you help me?

**Comment by mikey-austin** [comment]
Hey Helio,

On 03/07/16 19:57, Helio Loureiro wrote:
> Hi,
> 
> I started postfix on loopback listening at 25. Same for greyd on 8025.
> And I created the following rules:
> 
> iptables -t nat -A PREROUTING -p tcp --dport 25 -d -j REDIRECT --to-port
> 8025
> 
> It works fines, but I guess I need to create some chain to allow a
> connection toward port 25 on white list. If I manually add a rule before
> that one, like:
> 
> iptables -t nat -A PREROUTING -p tcp -s --dport 25 -d -j REDIRECT
> --to-port 25
> 
> But I guess it should be automatic. I miss some direction about that.
> Can you help me?

You are on the right track, but there are a couple of things:

1. Postfix should really be listening on all interfaces (0.0.0.0:25)

2. It's all about the ipsets. greyd will maintain the whitelist ipsets,
which is what the firewall rules make use of to redirect the traffic.
Here are my nat rules:


-A PREROUTING -p tcp --dport smtp -m set --match-set greyd-whitelist src
-j NFLOG --nflog-group 155
-A PREROUTING -p tcp --dport smtp -m set --match-set greyd-whitelist src
-j ACCEPT
-A PREROUTING -p tcp --dport smtp -j DNAT --to-destination 127.0.0.1:8025

The order of the above rules is important. Basically, if the remote host
is "whitelisted" (in the greyd-whitelist ipset, maintained by greyd),
then it will leave the nat table and go on to the usual filter rules
(allow port 25, etc.). If the host is not in the greyd-whitelist ipset,
the it will hit the 3rd rule above and get redirected to greyd on port 8025.

The first rule is for greylogd, which listens for whitelist connections
to update the expiration times.

Note, if you have greyd listening on loopback, the linux kernel doesn't
allow external traffic to be routed to loopback by default; you need to
set the following sysctl:

# sysctl net.ipv4.conf.eth0.route_localnet=1

The manual has much more detail in how the above works:

http://greyd.org/man.php?name=greyd

Hope that helps!

Mikey

**Comment by mikey-austin** [comment]
Hey Helio,

You are on the right track, but there are a couple of things: 

1. Postfix should really be listening on all interfaces (0.0.0.0:25) 
2. It's all about the ipsets. greyd will maintain the whitelist ipsets, which is what the firewall rules make use of to redirect the traffic. 

Here are my nat rules: 
```
-A PREROUTING -p tcp --dport smtp -m set --match-set greyd-whitelist src -j NFLOG --nflog-group 155
-A PREROUTING -p tcp --dport smtp -m set --match-set greyd-whitelist src -j ACCEPT
-A PREROUTING -p tcp --dport smtp -j DNAT --to-destination 127.0.0.1:8025 
```
The order of the above rules is important. Basically, if the remote host is "whitelisted" (in the greyd-whitelist ipset, maintained by greyd), then it will leave the nat table and go on to the usual filter rules (allow port 25, etc.). If the host is not in the greyd-whitelist ipset, the it will hit the 3rd rule above and get redirected to greyd on port 8025. 

The first rule is for greylogd, which listens for whitelist connections to update the expiration times. 

Note, if you have greyd listening on loopback, the linux kernel doesn't allow external traffic to be routed to loopback by default; you need to set the following sysctl: 

`# sysctl net.ipv4.conf.eth0.route_localnet=1`

The manual has much more detail in how the above works: http://greyd.org/man.php?name=greyd 

Hope that helps!

**Comment by helioloureiro** [comment]
Great!!!

That worked as well.  Since I'm using ufw as firewall, I just added the following rules:

*nat
-A PREROUTING -p tcp -m tcp --dport 25 -m set --match-set greyd-whitelist src -j LOG --log-prefix "[GREYD CHECKS]"
-A PREROUTING -p tcp -m tcp --dport 25 -m set --match-set greyd-whitelist src -j NFLOG --nflog-group 155
-A PREROUTING -p tcp -m tcp --dport 25 -m set --match-set greyd-whitelist src -j ACCEPT
-A PREROUTING -p tcp -m tcp --dport 25 -j LOG --log-prefix "[GREYD JAILED]"
-A PREROUTING -p tcp -m tcp --dport 25 -j DNAT --to-destination 127.0.0.1:8025
COMMIT

In order to create ipset, I changed /etc/init.d/greyd at start():

start() {
    ipset list greyd-whitelist > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        ipset create greyd-whitelist hash:ip family inet hashsize 1024 maxelem 65536
    fi

It seems to be working so far.
